name: Tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  FLUTTER_VERSION: "2.10.5"

jobs:
  tests:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Cache
        id: cache-flutter
        uses: actions/cache@v3.0.1
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter if not cached
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      # Checkout and get packages.
      - name: Checkout
        uses: actions/checkout@v2
      - run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - name: Run Unit Tests
        run: flutter test --coverage
      - name: Upload Coverage to Codecov
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v2

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        id: cache-flutter
        uses: actions/cache@v3.0.1
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter if not cached
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Add Flutter to PATH
        run: echo "$RUNNER_TOOL_CACHE/flutter/bin" >> $GITHUB_PATH
        shell: bash
      - name: Flutter doctor
        run: flutter doctor -v

      # Checkout and get packages.
      - name: Checkout
        uses: actions/checkout@v2
      - run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed --dry-run .

  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        id: cache-flutter
        uses: actions/cache@v3.0.1
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter if not cached
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Add Flutter to PATH
        run: echo "$RUNNER_TOOL_CACHE/flutter/bin" >> $GITHUB_PATH
        shell: bash
      - name: Flutter doctor
        run: flutter doctor -v

      # Checkout and get packages.
      - name: Checkout
        uses: actions/checkout@v2
      - run: flutter pub get

      - name: Analyze
        run: flutter analyze
